# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale

name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '0 8 * * 1'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Your issue has been marked as stale. Please remove stale label or comment or this will be closed in 30 days'
        stale-pr-message: 'Your PR has been marked as stale. Please remove stale label or comment or this will be closed in 30 days' 
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-issue-close: 30
        days-before-pr-close: 30

